global using AltoroSite_TestExploration.Drivers;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Playwright;
global using NUnit.Framework;
global using Reqnroll.BoDi;
global using Reqnroll;
global using System.Text.RegularExpressions;
global using UKBA_TestExploration.Config;
global using UKBA_TestExploration.Pages;